# Proyeksi Data

In [147]:
import numpy as np

# Assuming you have your input data stored as dictionaries or a list of dictionaries

data = [
    {'class': 1, 'X1': 2.95, 'X2': 6.63},
    {'class': 1, 'X1': 2.53, 'X2': 7.79},
    {'class': 1, 'X1': 3.57, 'X2': 5.65},
    {'class': 1, 'X1': 3.16, 'X2': 5.47},
    {'class': 2, 'X1': 2.58, 'X2': 4.46},
    {'class': 2, 'X1': 2.16, 'X2': 6.22},
    {'class': 2, 'X1': 3.27, 'X2': 3.52}
]

# Convert the data into a numpy array
X = np.array([[d['X1'], d['X2']] for d in data])
y = np.array([d['class'] for d in data])

# Get unique class labels
classes = np.unique(y)

# Calculate the total mean vector
mean_total = np.mean(X, axis=0)

In [112]:
import numpy as np

data = [
    {'class': 1, 'X1': 1, 'X2': 2},
    {'class': 1, 'X1': 2, 'X2': 3},
    {'class': 1, 'X1': 3, 'X2': 3},
    {'class': 1, 'X1': 4, 'X2': 5},
    {'class': 1, 'X1': 5, 'X2': 5},
    {'class': 2, 'X1': 4, 'X2': 2},
    {'class': 2, 'X1': 5, 'X2': 0},
    {'class': 2, 'X1': 5, 'X2': 2},
    {'class': 2, 'X1': 3, 'X2': 2},
    {'class': 2, 'X1': 5, 'X2': 3},
    {'class': 2, 'X1': 6, 'X2': 3}
]

# Convert the data into a numpy array
X = np.array([[d['X1'], d['X2']] for d in data])
y = np.array([d['class'] for d in data])

# Get unique class labels
classes = np.unique(y)

# Calculate the total mean vector
mean_total = np.mean(X, axis=0)

## Sw dan Sb

In [148]:
# Calculate the scatter matrices Sw_class and Sb
Sw_class1 = np.zeros((2, 2))
Sb1 = np.zeros((2, 2))

X_class = X[y == 1]
mean_class = np.mean(X_class, axis=0)
n_class = X_class.shape[0]
    
Sw_class1 += np.dot((X_class - mean_class).T, (X_class - mean_class))
Sb1 += n_class * np.outer((mean_class - mean_total), (mean_class - mean_total))
print(Sb1)
print(Sw_class1)

[[0.10749031 0.46415204]
 [0.46415204 2.00424694]]
[[ 0.562875 -1.23795 ]
 [-1.23795   3.4115  ]]


In [149]:
# Calculate the scatter matrices Sw_class and Sb
Sw_class2 = np.zeros((2, 2))
Sb2 = np.zeros((2, 2))

X_class2 = X[y == 2]
mean_class2 = np.mean(X_class2, axis=0)
n_class2 = X_class2.shape[0]
    
Sw_class2 += np.dot((X_class2 - mean_class2).T, (X_class2 - mean_class2))
Sb2 += n_class2 * np.outer((mean_class2 - mean_total), (mean_class2 - mean_total))
print(Sb2)
print(Sw_class2)

[[0.14332041 0.61886939]
 [0.61886939 2.67232925]]
[[ 0.6282     -1.4616    ]
 [-1.4616      3.75706667]]


In [150]:
Sb = Sb1 + Sb2
Sb

array([[0.25081071, 1.08302143],
       [1.08302143, 4.67657619]])

## W + eigen value + eigen Vector

In [151]:
# Calculate the eigenvalues and eigenvectors for each class
W_class1 =np.dot(np.linalg.inv(Sw_class1), Sb)
print(W_class1)

[[ 5.66471321 24.4607006 ]
 [ 2.37304797 10.24701759]]


In [162]:
eigenvalues1, eigenvectors1 = np.linalg.eig(W_class1)
print(eigenvalues1[1])
print(eigenvectors1[1])

15.911730794893117
[ 0.22561331 -0.38638367]


In [153]:
max_discriminant_index = np.argmax(eigenvalues1)
max_discriminant_eigenvalue = eigenvalues1[max_discriminant_index]
max_discriminant_eigenvector = eigenvectors1[:, max_discriminant_index]

# Perform projection
projected_data = np.dot(X_class, max_discriminant_eigenvector)
projected_data

array([-5.28262126, -5.34344429, -5.47581492, -5.02810722])

In [154]:
X_class

array([[2.95, 6.63],
       [2.53, 7.79],
       [3.57, 5.65],
       [3.16, 5.47]])

In [155]:
max_discriminant_eigenvalue

15.911730794893117

In [156]:
max_discriminant_eigenvector

array([-0.92233815, -0.38638367])

### buat class 2

In [157]:
W_class2 =np.dot(np.linalg.inv(Sw_class2), Sb)
W_class2

array([[11.27776099, 48.69830563],
       [ 4.6756149 , 20.18969223]])

In [158]:
eigenvalues2, eigenvectors2 = np.linalg.eig(W_class2)
print(eigenvalues2)
print(eigenvectors2)

[ 0.         31.46745322]
[[-0.97421693 -0.92375747]
 [ 0.22561331 -0.38297799]]


In [159]:
max_discriminant_index = np.argmax(eigenvalues2)
max_discriminant_eigenvalue = eigenvalues2[max_discriminant_index]
max_discriminant_eigenvector = eigenvectors2[:, max_discriminant_index]

# Perform projection
projected_data = np.dot(X_class2, max_discriminant_eigenvector)
projected_data

array([-4.09137609, -4.37743921, -4.36876944])

In [144]:
X_class2

array([[2.58, 4.46],
       [2.16, 6.22],
       [3.27, 3.52]])

In [145]:
max_discriminant_eigenvalue

31.46745322122128

In [146]:
max_discriminant_eigenvector

array([-0.92375747, -0.38297799])

# Klasifikasi Data

In [21]:
import numpy as np

data = [
    {'class': 1, 'X1': 1, 'X2': 2},
    {'class': 1, 'X1': 2, 'X2': 3},
    {'class': 1, 'X1': 3, 'X2': 3},
    {'class': 1, 'X1': 4, 'X2': 5},
    {'class': 1, 'X1': 5, 'X2': 5},
    {'class': 2, 'X1': 4, 'X2': 2},
    {'class': 2, 'X1': 5, 'X2': 0},
    {'class': 2, 'X1': 5, 'X2': 2},
    {'class': 2, 'X1': 3, 'X2': 2},
    {'class': 2, 'X1': 5, 'X2': 3},
    {'class': 2, 'X1': 6, 'X2': 3}
]

# Convert the data into a numpy array
X = np.array([[d['X1'], d['X2']] for d in data])
y = np.array([d['class'] for d in data])

# Get unique class labels
classes = np.unique(y)

# Calculate the total mean vector
mean_total = np.mean(X, axis=0)

In [22]:
mean_total

array([3.90909091, 2.72727273])

In [72]:
import numpy as np

data = [
    {'class': 1, 'X1': 54, 'X2': 72},
    {'class': 1, 'X1': 50, 'X2': 72},
    {'class': 1, 'X1': 48, 'X2': 56},
    {'class': 1, 'X1': 44, 'X2': 72},
    {'class': 1, 'X1': 47, 'X2': 64},
    {'class': 1, 'X1': 35, 'X2': 64},
    {'class': 1, 'X1': 36, 'X2': 56},
    {'class': 2, 'X1': 52, 'X2': 56},
    {'class': 2, 'X1': 23, 'X2': 56},
    {'class': 2, 'X1': 40, 'X2': 45},
    {'class': 2, 'X1': 34, 'X2': 56},
    {'class': 2, 'X1': 26, 'X2': 29},
    {'class': 2, 'X1': 25, 'X2': 56},
    {'class': 2, 'X1': 27, 'X2': 56},
    {'class': 2, 'X1': 29, 'X2': 30}
]

# Convert the data into a numpy array
X = np.array([[d['X1'], d['X2']] for d in data])
y = np.array([d['class'] for d in data])

# Get unique class labels
classes = np.unique(y)

# Calculate the total mean vector
mean_total = np.mean(X, axis=0)

In [73]:
mean_total

array([38., 56.])

## Class 1

In [80]:
# Calculate the scatter matrices Sw_class and Sb
Sw_class1 = np.zeros((2, 2))
Sb1 = np.zeros((2, 2))

X_class1 = X[y == 1]
mean_class1 = np.mean(X_class1, axis=0)
n_class1 = X_class1.shape[0]
    
Sw_class1 += np.dot((X_class1 - mean_class1).T, (X_class1 - mean_class1))
Sb1 += n_class1 * np.outer((mean_class1 - mean_total), (mean_class1 - mean_total))
print(Sb1)
print(Sw_class1)

[[329.14285714 438.85714286]
 [438.85714286 585.14285714]]
[[300.85714286 153.14285714]
 [153.14285714 310.85714286]]


In [81]:
p1 = n_class1/X.shape[0]
lognya1 = np.log(p1)
print(p1)
print(lognya1)

0.4666666666666667
-0.7621400520468967


## Class 2

In [82]:
# Calculate the scatter matrices Sw_class and Sb
Sw_class2 = np.zeros((2, 2))
Sb2 = np.zeros((2, 2))

X_class2 = X[y == 2]
mean_class2 = np.mean(X_class2, axis=0)
n_class2 = X_class2.shape[0]
    
Sw_class2 += np.dot((X_class2 - mean_class2).T, (X_class2 - mean_class2))
Sb2 += n_class2 * np.outer((mean_class2 - mean_total), (mean_class2 - mean_total))
print(Sb2)
print(Sw_class2)

[[288. 384.]
 [384. 512.]]
[[ 668.  152.]
 [ 152. 1014.]]


In [83]:
p2 = n_class2/X.shape[0]
lognya2 = np.log(p2)
print(p2)
print(lognya2)

0.5333333333333333
-0.6286086594223742


## Hitung Sp

In [84]:
sp11 = (((n_class1-1)/(X.shape[0]-1))*Sw_class1[0][0])+(((n_class2-1)/(X.shape[0]-1))*Sw_class2[0][0])
sp22 = (((n_class1-1)/(X.shape[0]-1))*Sw_class1[1][1])+(((n_class2-1)/(X.shape[0]-1))*Sw_class2[1][1])
sp12 = (((n_class1-1)/(X.shape[0]-1))*Sw_class1[0][1])+(((n_class2-1)/(X.shape[0]-1))*Sw_class2[0][1])

In [85]:
sp = np.array([[sp11,sp12],[sp12,sp22]])
sp

array([[462.93877551, 141.63265306],
       [141.63265306, 640.2244898 ]])

In [86]:
sp_inv = np.linalg.inv(sp)
sp_inv

array([[ 0.00231693, -0.00051256],
       [-0.00051256,  0.00167534]])

## 4. menghitung hasil matriks

### Class 1

In [87]:
a = (-1/2)*np.dot(np.dot(mean_class1,sp_inv),(mean_class1).T)
a

-4.38799255771177

### Class 2

In [88]:
b = (-1/2)*np.dot(np.dot(mean_class2,sp_inv),(mean_class2).T)
b

-2.3289706296255015

## 5. menghitung hasil matriks untuk x baru

In [89]:
x_baru = np.array([20,55])
x_baru

array([20, 55])

### Class 1

In [90]:
a1 = np.dot(np.dot(mean_class1,sp_inv),(x_baru).T)
a1

6.148780011937608

### Class 2

In [91]:
b1 = np.dot(np.dot(mean_class2,sp_inv),(x_baru).T)
b1

4.511577045201738

## 6. Fungsi Diskriminan

In [92]:
sl1= a + a1 + lognya1
sl2= b + b1 + lognya2
sl = np.array([sl1,sl2])
sl

array([0.9986474 , 1.55399776])

In [93]:
max_sl = np.argmax(sl)
max_sl

1

In [71]:
print('maka', x_baru, 'diklasifikasikan ke class', (max_sl+1))

maka [4 0] diklasifikasikan ke class 2
